[package]

name = "cookie"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.0.1"

[dependencies.openssl]
git = "https://github.com/sfackler/rust-openssl"

[dependencies.url]
git = "https://github.com/servo/rust-url"

[dependencies.time]
git = "https://github.com/rust-lang/time"
