[package]

name = "cookie"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.2.4"
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/cookie-rs"
documentation = "http://alexcrichton.com/cookie-rs"
description = """
Crate for parsing HTTP cookie headers and managing a cookie jar. Supports
encrypted, signed, and permanent cookie chars composed together in a manner
similar to Rails' cookie jar.
"""

[features]
default = ["secure"]
serialize-rustc = ["rustc-serialize", "time/rustc-serialize"]
secure = ["openssl", "rustc-serialize"]
serialize-serde = ["serde"]

[dependencies]
url = "1.0"
time = "0.1"
rustc-serialize = { version = "0.3", optional = true }
openssl = { version = "0.7.0", optional = true }
serde = { version = "0.7.5", optional = true }

[dev-dependencies]
serde_json = "0.7.0"
