[package]

name = "cookie"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.1.18"
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/cookie-rs"
documentation = "http://alexcrichton.com/cookie-rs"
description = """
Crate for parsing HTTP cookie headers and managing a cookie jar. Supports
encrypted, signed, and permanent cookie chars composed together in amanner
similar to Rails' cookie jar.
"""

[dependencies]
openssl = "0.6.0"
url = "0.2"
time = "0.1"
rustc-serialize = "0.3"
